version: '3.8'

services:
  analysis-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static:/app/static
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped 